# docker-compose.yml
version: '3.7'
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@18@postgres:5432/cloud-backup
      NODE_ENV: development
      APP_PORT: 3000
      JWT_SECRET: Secret
      JWT_EXPIRES: 900
      JWT_REFRESH_TOKEN_EXPIRES:
      AWS_S3_ACCESS_KEY_ID: AKIAYSXUWOY4K2BCW73M
      AWS_S3_REGION: eu-west-2
      AWS_S3_ACCESS_KEY_SECRET: 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
      AWS_S3_BUCKET: octocare-dev
      REDIS_URL: redis://localhost:6379
      CACHE_TTL: 300
      REFRESH_CACHE_TTL: 3000
    expose:
      - "3306"
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:15.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@18
      POSTGRES_DB: cloud-backup
    env_file: .env